version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:latest
    volumes: 
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=qpaistaf_qpai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: kpi-phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "8000:80"